GE-6747 Apply bucket region fix

diff --git a/pipeline b/pipeline
--- a/pipeline
+++ b/pipeline
@@ -2,6 +2,29 @@
 
 bucket_name="twelve-factor-app-service-staging"
 package_name="twelve-factor-backing-service-$(uuidgen).zip"
+stack_name="twelve-factor-backing-service-stack"
+aws_region=$(aws configure get region)
+
+# args (bucket-name, region)
+function prepareBucket {
+  echo "Creating staging bucket if necessary"
+  if [ -z "$(aws s3api head-bucket --bucket "$1" 2>&1)" ]
+  then
+    echo "bucket exists, verifying region..."
+    bucket_region=$(aws s3api get-bucket-location --bucket "$1" | jq .LocationConstraint | tr -d '"')
+    if [ "$bucket_region" != "$2" ]
+    then
+      echo "Error: The staging bucket '$1' already exists in region $bucket_region"
+      exit 1
+    fi
+  else
+    echo "Info: The staging bucket does not yet exist and will be created in your configured region $aws_region"
+    aws s3api create-bucket --bucket "$1" --region "$2" --create-bucket-configuration LocationConstraint="$2"
+  fi
+}
+
+# main
+echo "The stack will deployed in region $aws_region"
 
 # build the application binary
 echo "Building binary"
@@ -13,17 +36,17 @@ rm -rf "$package_name"
 zip -j "$package_name" build/libs/*.jar
 
 # stage it
-echo "Creating staging bucket if necessary"
-[ "$(aws s3api head-bucket --bucket $bucket_name 2>&1 > /dev/null)" ] \
-  && (aws s3api create-bucket --bucket "$bucket_name" --region eu-central-1 \
-  --create-bucket-configuration LocationConstraint=eu-central-1)
+prepareBucket "$bucket_name" "$aws_region"
 echo "Staging to $bucket_name"
 aws s3 cp "$package_name" "s3://$bucket_name"
 
 # spin up / refresh environment
-cd cloudformation
-./build "$package_name"
-cd ..
+aws cloudformation deploy \
+  --capabilities CAPABILITY_IAM \
+  --stack-name $stack_name \
+  --template-file cloudformation/backing-service-app.yml \
+  --parameter-overrides \
+      PackageName="$package_name"
 
 echo "Remove staging"
 aws s3 rm s3://"$bucket_name"/"$package_name"
